### ISSUE TITLE
	Docs: what: point descriptions of each class/function (in isolation)

### ISSUE THREAD

**Issue by jayjagtap** [jayjagtap/Autofill-Buddy#18]
Documentation on function level, add to wiki

**Comment by VineetMakharia** [comment]
Is there a wiki page already created where I can add this documentation?

**Comment by VineetMakharia** [comment]
Started writing wiki page. Added basic information there, still work in progress.

**Comment by VineetMakharia** [comment]
Need help with this!

**Comment by git-ankit** [comment]
It has been added.
